### ISSUE TITLE
🐛 Bug Report: Collsion between Account Model between appwrite import

### ISSUE THREAD

**Issue by Vedsaga** [appwrite/sdk-generator#631] opened 2023-03-18 19:28 UTC
### 👟 Reproduction steps

```dart
import 'package:appwrite/appwrite.dart';
import 'package:appwrite/models.dart' ;

class Appwrite {
  static final _clientInstance = Client()
    ..setEndpoint(AppWriteConst.endpoint)
    ..setProject(AppWriteConst.projectId)
    ..setSelfSigned();
  static final _databaseInstance = Databases(_clientInstance);
  static final realTimeInstance = Realtime(_clientInstance);
  static final accountInstace = Account(_clientInstance);
}
```
Please copy paste this. Version is ` appwrite: ^8.3.0` in flutter project.

### 👍 Expected behavior

It is expected that class `Account` would be defined at only one place.

### 👎 Actual Behavior

But, currently account class is defined at two place due to that I have to use import like this,
```dart
import 'package:appwrite/appwrite.dart';
import 'package:appwrite/models.dart' hide Account;
```

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Something else

### 🧱 Your Environment

I used `pubspec.yaml`
` appwrite: ^8.3.0`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-03-29 00:40
Closing as a duplicate of https://github.com/appwrite/sdk-for-flutter/issues/93

**Closed by stnguyen90** 2023-03-29 00:40 UTC
Labels: bug
