### ISSUE TITLE
🐛 Bug Report: Error accountCreateEmailSession is not a function

### ISSUE THREAD

**Issue by buckbrady** [appwrite/sdk-generator#796] opened 2024-03-12 08:57 UTC
### 👟 Reproduction steps

running `appwrite login` with v5.0.0 of the cli the action fails with the following error

`Error accountCreateEmailSession is not a function`

### 👍 Expected behavior

The cli should successfully login to the appwrite instance

### 👎 Actual Behavior

Login fails

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite cli v5.0.0
appwrite v1.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2024-03-14 09:04
Closing as a duplicate of https://github.com/appwrite/sdk-for-cli/issues/116

**Closed by stnguyen90** 2024-03-14 09:04 UTC
Labels: bug
